version: '3'
services:

  ssdd-frontend:
    image: 127.0.0.1:5000/dsevilla/ssdd-frontend
    ports:
      - 5001:5000
    env_file: mongo.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_DEBUG=true

  db-mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017 
    env_file: mongo.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=ssdd

  backend-rest:
    image: 127.0.0.1:5000/dsevilla/ssdd-backend-rest
    ports:
      - 8080:8080
    env_file: mongo.env

  backend-rest-extern:
    image: 127.0.0.1:5000/dsevilla/ssdd-backend-rest-extern
    ports:
      - 8180:8180
    env_file: mongo.env
    
  backend-grpc:
    image: 127.0.0.1:5000/dsevilla/ssdd-backend-grpc
    ports:
      - 50051:50051
    env_file: mongo.env

